# Generated by Django 5.2.17 on 2026-09-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.CharField(choices=[('order_delivery', 'Order / delivery'), ('courses', 'Courses'), ('partnership', 'Partnership'), ('other', 'Other')], default='other', max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studio_name', models.CharField(default='Klara Cheesecakes', max_length=120)),
                ('whatsapp_number', models.CharField(help_text="E.164 format, digits only, e.g. 996700123456 (no '+').", max_length=32)),
                ('whatsapp_default_message', models.TextField(default="Hi! I'd like to order: {order_summary}. Total: {total} {currency}. Order #{order_number}.", help_text='Template used to build the prefilled WhatsApp message. Supports {order_summary}, {total}, {currency}, {order_number}, {customer_name}.')),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=32)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('working_hours', models.CharField(blank=True, max_length=255)),
                ('instagram_url', models.URLField(blank=True)),
                ('telegram_url', models.URLField(blank=True)),
                ('tiktok_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
    ]
