# Generated by Django 5.2.17 on 2026-09-02 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import backend


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('cakes', '0001_initial'),
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                           related_name='carts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('delivery_date', models.DateField(blank=True, help_text='Cheesecake items only.', null=True)),
                ('special_request', models.CharField(blank=True, max_length=255)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items',
                                           to='orders.cart')),
                ('cheesecake_variant',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                   related_name='cart_items', to='cakes.cheesecakevariant')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                             related_name='cart_items', to='courses.course')),
            ],
            options={
                'ordering': ['added_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_number',
                 models.CharField(default=backend.apps.orders.models.generate_order_number, max_length=20,
                                  unique=True)),
                ('order_type',
                 models.CharField(choices=[('cheesecake', 'Cheesecake'), ('course', 'Course'), ('mixed', 'Mixed')],
                                  max_length=12)),
                ('status', models.CharField(
                    choices=[('new', 'New'), ('awaiting_whatsapp_contact', 'Awaiting WhatsApp contact'),
                             ('awaiting_payment', 'Awaiting payment'), ('paid', 'Paid'), ('processing', 'Processing'),
                             ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='new', max_length=30)),
                ('contact_name', models.CharField(max_length=160)),
                ('contact_phone', models.CharField(max_length=32)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('delivery_method', models.CharField(
                    choices=[('courier', 'Courier'), ('express', 'Express courier'), ('pickup', 'Studio pickup'),
                             ('n_a', 'Not applicable (digital order)')], default='n_a', max_length=10)),
                ('delivery_city', models.CharField(blank=True, max_length=120)),
                ('delivery_street', models.CharField(blank=True, max_length=255)),
                ('delivery_apartment', models.CharField(blank=True, max_length=40)),
                ('delivery_floor', models.CharField(blank=True, max_length=20)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('delivery_comment', models.TextField(blank=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('promo_code', models.CharField(blank=True, max_length=40)),
                ('whatsapp_contacted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, help_text='Null for guest cheesecake-only orders.', null=True,
                                           on_delete=django.db.models.deletion.SET_NULL, related_name='orders',
                                           to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type',
                 models.CharField(choices=[('cheesecake', 'Cheesecake'), ('course', 'Course')], max_length=12)),
                ('name_snapshot', models.CharField(max_length=200)),
                ('variant_snapshot', models.CharField(blank=True, max_length=120)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('cheesecake', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                 related_name='order_items', to='cakes.cheesecake')),
                ('cheesecake_variant',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                   to='cakes.cheesecakevariant')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                             related_name='order_items', to='courses.course')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items',
                                            to='orders.order')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user',),
                                               name='unique_cart_per_user'),
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(condition=models.Q(('session_key__isnull', False)),
                                               fields=('session_key',), name='unique_cart_per_session'),
        ),
    ]
