# Generated by Django 5.2.17 on 2026-09-02 09:53
import django.db.models.deletion
from django.db import migrations, models

import backend


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheesecakeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=90, unique=True)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Cheesecake categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryBlackoutDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('reason', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Cheesecake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=140)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('short_description', models.CharField(blank=True, max_length=280)),
                ('description', models.TextField(blank=True)),
                ('ingredients', models.JSONField(blank=True, default=list,
                                                 help_text='List of ingredient strings, e.g. ["Cream cheese", "Eggs", ...].')),
                ('allergen_info', models.CharField(blank=True, max_length=255)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('badge', models.CharField(blank=True, choices=[('bestseller', 'Bestseller'), ('seasonal', 'Seasonal'),
                                                                ('new', 'New'), ('gift', 'Gift'), ('', 'None')],
                                           max_length=20)),
                ('is_vegan', models.BooleanField(default=False)),
                ('is_gluten_free', models.BooleanField(default=False)),
                ('prep_hours', models.PositiveIntegerField(default=48,
                                                           help_text='Minimum lead time before the earliest delivery date.')),
                ('is_available', models.BooleanField(default=True,
                                                     help_text='Turn off to hide from the shop without deleting it (sold out/paused).')),
                ('status',
                 models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')],
                                  default='active', max_length=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cheesecakes',
                                               to='cakes.cheesecakecategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CheesecakeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image',
                 models.URLField(help_text='Image URL (swap for an ImageField + storage backend in production).')),
                ('alt_text', models.CharField(blank=True, max_length=180)),
                ('is_primary', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('cheesecake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images',
                                                 to='cakes.cheesecake')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CheesecakeReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author_name', models.CharField(max_length=120)),
                ('rating', models.PositiveSmallIntegerField(validators=[backend.apps.common.models.validate_rating])),
                ('text', models.TextField()),
                ('is_approved',
                 models.BooleanField(default=True, help_text='Unapproved reviews are hidden from the public API.')),
                ('cheesecake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews',
                                                 to='cakes.cheesecake')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CheesecakeVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. "Medium"', max_length=80)),
                ('portion_note', models.CharField(blank=True, help_text='e.g. "8-10 servings"', max_length=80)),
                ('price_delta', models.DecimalField(decimal_places=2, default=0,
                                                    help_text="Added to the cheesecake's base_price for this size.",
                                                    max_digits=10)),
                ('is_default', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('cheesecake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants',
                                                 to='cakes.cheesecake')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'unique_together': {('cheesecake', 'name')},
            },
        ),
    ]
